name: Build

on:
  push:
    branches: [source]
  pull_request:
    branches: [source]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13.x

      - name: Install node modules
        uses: bahmutov/npm-install@v1

      - name: Build
        run: yarn build

      - name: Deploy GitHub Pages
        if: github.ref == 'refs/heads/source'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          publish_branch: master
          force_orphan: true
